### ISSUE TITLE
Work with Dr. Sepulveda to obtain EPIC data

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#82]

**Comment by lorikrammer** [comment]
Met with Urnisha today to discuss next steps for the EPIC Data Model: 

- [ ] Confirm variables & codes with Dr. Sepulveda
- [ ] Provide cohort design documentation & confirm desired output, provide template excel sheet
- [ ] Provide scripts for Dr. Sepulveda to run within COSMOS
- [ ] Follow up on package and test it with MDClone/publicly available data.

**Comment by ubhuiyan** [comment]
All data retrieved  thus far can be viewed within the collaborative notebook: 

[PreDM Keto Diet Epic Cosmos Cohort Data](https://gwu0.sharepoint.com/sites/PredictModCollaborators-GRP/_layouts/15/Doc.aspx?sourcedoc={345b5337-4c8f-40cb-8dd8-cfccdc2178cb}&action=edit&wd=target%28Preliminary%20Findings.one%7Cc0a64da3-8c13-4b7f-b90b-c646240c0115%2FDiets%7C7b2dc539-2423-416c-9489-0a54c4d13ced%2F%29&wdorigin=NavigationUrl)

**Comment by ubhuiyan** [comment]
**Updates:**

**7/11/23**
Identified the ketogenic diet as having the most patient observations available compared to all other diet types. 
631 patients with a prediabetes diagnosis were found to be on the ketogenic diet 
This number reduces to 487 patients when looking into how many patients have a documented weight prior to and during/after diet intervention 

**7/18/23** 
Established we were interested in looking into a patient's max weight 90 days prior to beginning the intervention, and minimum weight 158 days prior to the start of the intervention (this yielded the max number of patients at around 308) to determine R/NR outcome. 
As of now, we see a 40% response rate to the ketogenic diet where 121=R and 187=NR

**7/25/23**
We used the PredictMod EHR Query document which is an extension of the MDClone Query document to isolate all variables of interest. 
We filtered through all variables (as some were repeated multiple times), and referred to Dr. Sepulveda's expertise on which repeated variables to keep and later aggregate or which ones to remove entirely. 
A few variables were not very searchable with the LOINC codes or with their abbreviated names like CO2, so we had to do a manual search for those items.
Ex. Search for carbon dioxide instead of CO2 

**8/1/23**
We were able to successfully aggregate all variables of interest 
We are conducting QC on the ranges for all variables to make sure there are no outliers or incorrect submissions. 
Part of the QC entailed looking at the overall distribution of each variable to make sure the majority looks similar to a bell curve. 
Ex. One individual had creatinine recorded at 200 but the highest recorded creatinine measurement in the literature was 76. We will likely remove patients that have clear incorrect records documented. So far, only one patient seems to be a true outlier.  

**8/8/23**
Dr. Sepluveda provided me with the list of variables we have agreed upon to aggregate according to the PredictMod EHR Query document. 
I will use this to create a sub-data dictionary for PredictMod EHR
After having satisfactory ranges for each variable, we added these ranges to the master table to comprise the latest lab result for each patient.
We created a preliminary readme table that may go hand in hand with the sub-data dictionary. 

**Next Steps:**
Complete cleaning data table - Projected Completion: ~August 29th 
Model Training - Projected Start: ~August 29th or September 5th

**Comment by ubhuiyan** [comment]
**8/25/23**
Added smoking status to data table 
- Individuals with no evidence of smoking cessation will be deemed current smoker
- Evidence of cessation will be deemed past smoker
- No evidence of smoking will be deemed never smoker
The smoking status was then merged with the master table labeled moddt 
- This was to identify which of the preDM patients are current, past, never smokers 
Some patients needed their smoking status to be determined manually given they had varying start and stop dates

**Comment by ubhuiyan** [comment]
**8/29/23**

- All variables of interest were added to the PredictMod EHR Table
- Birthdate was converted to age for simplicity 
- Data table was uploaded into virtual VS Code in Cosmos platform 
- Table is ready for model training

**Next Steps:**
Projected Model Training: September 5th - On Time

**Comment by ubhuiyan** [comment]
9/5/23

- Data has been cleaned and model testing has begun 
- Current accuracy only falls at around 60% 
- Will export this preliminary model prior to improving model accuracy 
- Next meeting will be 10/10/23

**Comment by ubhuiyan** [comment]
**10/11/23**

- Tested a random forest tree with the data and had an improvement in model performance
- Generated feature importance and confusion matrices for the random forest to compare to the decision tree 
- Pickled the random forest model  

**Next Steps:** 
- Will need to create a rotation forest from scratch given pip install is not allowed within the Cosmos platform 
- Will need to determine alternative tree based models that we can use to get better accuracy
- Dr. Sepulveda will run the data table through a tool in R that functions similarly to the Classification Learner Application in MATLAB to see what model performs best on his end

**Comment by ubhuiyan** [comment]
**10/17/23**

- Test an SVM model with linear, RBF, and Sigmoid kernels
- Improved Model Accuracy to 65% (this is improvement from a random forest at 60%) 
- Pickled SVM model 

**Next Steps:** 

- Will determine what export file to use based on decision by folks at Epic 
- Tweak feature importance code for SVM model 
- Update dataset with new data from latest Epic update

**Comment by ubhuiyan** [comment]
**11/1/23**

- Converted pickle file into a txt file and are awaiting permission to transport packaged model 
- Discussed Data Dictionary and will apply edits as suggested by Dr. Sepulveda 

**Next Steps:**

- Should there be issues with transferring the packaged model, Dr. Sepulveda, Dr. Mazumder, Pat, and I will need to have further discussions to determine a solution. 
- Work on data dictionary
